project:
  type: website
  output-dir: docs

website:
  title: "Spinning Synth E155 Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: system-overview.qmd
        text: Overview
      - href: hardware.qmd
        text: Hardware
      - href: fpga.qmd
        text: FPGA
      - href: mcu.qmd
        text: MCU
      - href: results.qmd
        text: Results
      - href: team.qmd
        text: Team
      - href: references.qmd
        text: References
      - href: acknowledgements.qmd
        text: Acknowledgements
  page-navigation: true
  search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: show
    smooth-scroll: true

filters:
  - quarto

execute:
  freeze: auto




